from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from app.domains.integrity.plagiarism.analyzer import PlagiarismReport


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def render_plagiarism_html(report: PlagiarismReport) -> str:
    rows = []
    for src in report.per_source:
        rows.append(
            "<tr>"
            f"<td>{html.escape(str(src.get('doc_id','')))}</td>"
            f"<td>{html.escape(str(src.get('doc_path','')))}</td>"
            f"<td style='text-align:right'>{html.escape(_pct(float(src.get('matched_percent',0.0))))}</td>"
            "</tr>"
        )

    match_cards = []
    for m in report.matches[:50]:
        phrases_html = "".join(
            f"<li><code>{html.escape(p)}</code></li>" for p in (m.shared_phrases or [])
        )
        match_cards.append(
            "<div class='card'>"
            f"<div class='meta'><b>Score</b> {m.score:.3f} | <b>Query chunk</b> #{m.query_chunk_id} | <b>Source</b> {html.escape(m.source_doc_id)} (chunk #{m.source_chunk_id})</div>"
            f"<div class='grid'>"
            f"<div><h4>Query</h4><pre>{html.escape(m.query_text)}</pre></div>"
            f"<div><h4>Source</h4><pre>{html.escape(m.source_text)}</pre></div>"
            f"</div>"
            f"<div><h4>Evidence phrases</h4><ul>{phrases_html or '<li><i>No long shared phrases found (likely paraphrase).</i></li>'}</ul></div>"
            "</div>"
        )

    return f"""<!doctype html>
<html>
<head>
  <meta charset='utf-8' />
  <meta name='viewport' content='width=device-width, initial-scale=1' />
  <title>EduGuard Plagiarism Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; }}
    .kpi {{ display:flex; gap:16px; flex-wrap:wrap; margin: 16px 0; }}
    .pill {{ border:1px solid #ddd; border-radius:12px; padding:12px 14px; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border-bottom: 1px solid #eee; padding: 8px; vertical-align: top; }}
    th {{ text-align: left; }}
    pre {{ white-space: pre-wrap; word-wrap: break-word; background:#fafafa; border:1px solid #eee; padding:10px; border-radius:10px; }}
    .card {{ border:1px solid #eee; border-radius:16px; padding:14px; margin: 14px 0; }}
    .meta {{ color:#333; margin-bottom:10px; }}
    .grid {{ display:grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
    @media (max-width: 900px) {{ .grid {{ grid-template-columns: 1fr; }} }}
    code {{ background:#f2f2f2; padding:2px 6px; border-radius:6px; }}
  </style>
</head>
<body>
  <h1>Plagiarism Report</h1>
  <div class='kpi'>
    <div class='pill'><b>Query file</b><div>{html.escape(report.query_file)}</div></div>
    <div class='pill'><b>Corpus</b><div>{html.escape(report.corpus_dir)}</div></div>
    <div class='pill'><b>Model</b><div>{html.escape(report.model_name)}</div></div>
    <div class='pill'><b>Overall similarity</b><div style='font-size:20px'><b>{_pct(report.overall_similarity)}</b></div></div>
  </div>

  <h2>Source breakdown</h2>
  <table>
    <thead><tr><th>doc_id</th><th>path</th><th style='text-align:right'>share</th></tr></thead>
    <tbody>
      {''.join(rows) if rows else '<tr><td colspan=3><i>No matches above threshold.</i></td></tr>'}
    </tbody>
  </table>

  <h2>Top evidence matches</h2>
  {''.join(match_cards) if match_cards else '<i>No matches above threshold.</i>'}

  <hr />
  <div style='color:#666'>Generated by EduGuard CLI</div>
</body>
</html>"""


def save_plagiarism_html(report: PlagiarismReport, out_path: str | Path) -> None:
    out_p = Path(out_path)
    out_p.parent.mkdir(parents=True, exist_ok=True)
    out_p.write_text(render_plagiarism_html(report), encoding="utf-8")
